BigInteger Solution
Danverr/HSE-Course pull request #1
Opened 2020-10-05 11:14 UTC by Danverr

Маряхин Даниил Денисович

2020-10-05 11:33 UTC, lgAshanl requested changes

2020-10-05 11:33 UTC, lgAshanl commented on module-1/homework/BigInteger/tests.cpp
> +	ASSERT_EQ(oss.str(), std::to_string(value));
Не стоит менять тесты. Добавляй в реп файлы по-одному, только нужные. В идеале только biginteger.cpp(.h)

2020-10-05 11:33 UTC, lgAshanl commented on module-1/homework/BigInteger/biginteger.h
> +
Сначала публичные: программисту интересно в первую очередь, как с классом можно работать, а потом уже, как он реализован внутри

2020-10-05 11:33 UTC, lgAshanl commented on module-1/homework/BigInteger/biginteger.cpp
> +}
Стоит через список инициализации сделать

2020-10-05 11:33 UTC, lgAshanl commented on module-1/homework/BigInteger/biginteger.cpp
> +	return *this;
Проверить, не присваивается ли объект сам себе

2020-10-05 11:33 UTC, lgAshanl commented on module-1/homework/BigInteger/biginteger.cpp
> +	return *this + (-x);
Лишний объект (-x) на стеке. Попробуй через -=

2020-10-05 11:33 UTC, lgAshanl commented on module-1/homework/BigInteger/biginteger.cpp
> +}
У тебя оператор + честно создает BigInteger на стеке. Оно и понятно: ему надо вернуть честный объект, а не ссылку. += же в свою очередь возврачает ссылку (надо бы поправить и это), а значит можно избежать создания BigInteger (конструктор/деструктор, вот это всё) и не копировать в this, а менять this "на месте". Поэтому часто аккуратно реализуют +=, а потом уже через него +, а у тебя наоборот. C остальными операторами то же.

2020-10-06 07:27 UTC, Danverr commented on module-1/homework/BigInteger/biginteger.cpp
> +}
Т.е. так?
`BigInteger::BigInteger() : digits({0}), sign(1) { }`

2020-10-06 07:27 UTC, Danverr commented on module-1/homework/BigInteger/biginteger.cpp
> +}
> Стоит через список инициализации сделать

Т.е. так?
`BigInteger::BigInteger() : digits({0}), sign(1) { }`

2020-10-06 07:30 UTC, Danverr commented on module-1/homework/BigInteger/biginteger.cpp
> +	return *this;
> Проверить, не присваивается ли объект сам себе

Чтобы не тратить время на присвоение лишний раз?

2020-10-07 22:24 UTC, lgAshanl commented on module-1/homework/BigInteger/biginteger.cpp
> +	return *this;
Да, но не только. Иногда присваивание самому себе может быть некорректно

2020-10-07 22:24 UTC, lgAshanl commented on module-1/homework/BigInteger/biginteger.cpp
> +}
Именно

2020-10-17 19:08 UTC, lgAshanl commented on module-1/homework/BigInteger/biginteger.cpp
> +	int operation = sign * x.sign * (minus ? -1 : 1), ost = 0;
Если правильно понял, что тут происходит, ты можешь хранить sign в виде bool и тогда можно xor'ами обойтись. Ни условий, ни перемножений

2020-11-16 19:29 UTC, merged